apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  namespace: mssql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: mssql
    name: mssql-pvc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/mssql
    type: Directory