version: '3'

services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: always
    container_name: postgis
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - /mnt/data/postgis/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - bigdata

networks:
  bigdata:
    name: bigdata
    external: true