---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: client
  name: client
  namespace: hive
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - env:
        - name: DB_DRIVER
          value: postgres
        envFrom:
        - configMapRef:
            name: core-configmap
        image: localhost:5000/hive:4.1.0
        imagePullPolicy: Always
        name: client
