version: "3"

services:
  zookeeper:
    image: zookeeper:3.7.2
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - /mnt/data/zookeeper/data:/data
      - /mnt/data/zookeeper/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_ADMINSERVER_ENABLED: false
    networks:
      - bigdata

networks:
  bigdata:
    name: bigdata
    external: true
