apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: mongodb
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: mongodb
    name: mongodb-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/mongodb
    type: Directory