apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: mongodb-pv
  namespace: mongodbs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    name: mongodb-pvc
    namespace: mongodbs
  csi:
    driver: file.csi.azure.com
    volumeAttributes: 
      resourceGroup: {"resource_group_name"}_{"location"}
      storageAccount: {"storage_account_name"}
      shareName: {"share_name"}
      folderName: mongodb # MongoDB database folder
      server: {"storage_account_name"}.file.core.windows.net
      secretnamespace: mongodb
      secretName: mongodb-storage-secret
      skuName: Standard_LRS
    volumeHandle: {"resource_group_name"}_{"location"}#{"storage_account_name"}#{"share_name"}#mongodb
    nodeStageSecretRef:
      name: mongodb-storage-secret
      namespace: mongodbs
  mountOptions:
  - dir_mode=0700
  - file_mode=0600
  - uid=999
  - gid=999
  - cache=strict
  - mfsymlinks
  - nosharesock
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem