apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeMode: Filesystem
  volumeName: mongodb-pv
  resources:
    requests:
      storage: 20Gi
