apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-pvc
  namespace: hadoop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
  volumeName: hadoop-pv