apiVersion: v1
kind: PersistentVolume
metadata:
  name: hadoop-pv
  namespace: hadoop
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: hadoop
    name: hadoop-pvc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/hadoop
    type: Directory