apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
  namespace: zookeeper
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: zookeeper
    name: zookeeper-pvc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/zookeeper
    type: Directory