apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbclient
  namespace: dbclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbclient
  template:
    metadata:
      labels:
        app: dbclient
    spec:
      containers:
      - env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: dbclient-secret
              key: ssh-user
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbclient-secret
              key: ssh-password
        name: dbclient
        image: docker-registry.localhost/dbclient:24.04
        imagePullPolicy: Always
        ports:
        - containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: /mnt/backup
          name: dbclient-volume
          readOnly: false
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
      - name: dbclient-volume
        persistentVolumeClaim:
          claimName: dbclient-pvc      
