apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbclient-pv
  namespace: dbclient
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: dbclient
    name: dbclient-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/backup/databases
    type: Directory