apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbclient-pvc
  namespace: dbclient
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: hostpath
  volumeName: dbclient-pv