version: '3'

services:
  hivemetastore:
    image: carlchung/hive:3.1.3
    restart: always
    container_name: hivemetastore
    environment:
      DB_DRIVER: mysql
      SERVICE_NAME: 'metastore'
      METASTORE_PORT: 9083
      IS_RESUME: true
    ports:
      - '9083:9083'
    env_file:
      - ./hive.env
    networks:
      - bigdata
  
  hiveserver2:
    image: carlchung/hive:3.1.3
    depends_on:
      - hivemetastore
    restart: always
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    env_file:
      - ./hive.env
    networks:
      - bigdata

networks:
  bigdata:
    name: bigdata
    external: true