version: '3'

services:
  metastore:
    image: carlchung/hive:3.1.3
    restart: always
    container_name: hive-metastore
    environment:
      DB_DRIVER: mysql
      SERVICE_NAME: 'metastore'
    ports:
      - '9083:9083'
    env_file:
      - ./hive.env
    networks:
      - bigdata
  
  server2:
    image: carlchung/hive:3.1.3
    depends_on:
      - metastore
    restart: always
    container_name: hive-server2
    environment:
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    env_file:
      - ./hive.env
    networks:
      - bigdata

networks:
  bigdata:
    name: bigdata
    external: true
