apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: redis
    name: redis-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/d/db/redis
    type: Directory