apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-tls
  namespace: mysql
spec:
  dnsNames:
  - mysql.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: mysql-tls