apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-ssl-config
  namespace: mysql
data:
  ssl.cnf: |
    [mysqld]
    ssl-ca=/etc/mysql/ssl/ca.crt
    ssl-cert=/etc/mysql/ssl/tls.crt
    ssl-key=/etc/mysql/ssl/tls.key
    require_secure_transport=ON

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        image: mysql:8.0
        imagePullPolicy: Always
        name: mysql-app
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/mysql/conf.d/ssl.cnf
          subPath: ssl.cnf
          name: mysql-ssl-config
          readOnly: true
        - mountPath: /etc/mysql/ssl
          name: mysql-volume
          subPath: ssl
          readOnly: true
        - mountPath: /var/lib/mysql
          name: mysql-volume
          subPath: data
          readOnly: false
      restartPolicy: Always
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      volumes:
      - name: mysql-ssl-config
        configMap:
          name: mysql-ssl-config
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
