apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: mysql-pv
  namespace: mysql
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    name: mysql-pvc
    namespace: mysql
  csi:
    driver: file.csi.azure.com
    volumeAttributes: 
      resourceGroup: {"resource_group_name"}_{"location"}
      storageAccount: {"storage_account_name"}
      shareName: {"share_name"}
      folderName: mysql # MySQL database folder
      server: {"storage_account_name"}.file.core.windows.net
      secretnamespace: mysql
      secretName: mysql-storage-secret
      skuName: Standard_LRS
    volumeHandle: {"resource_group_name"}_{"location"}#{"storage_account_name"}#{"share_name"}#mysql
    nodeStageSecretRef:
      name: mysql-storage-secret
      namespace: mysql
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - cache=strict
  - mfsymlinks
  - nosharesock
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem