apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: mysql-pv
  namespace: mysql
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    name: mysql-pvc
    namespace: mysql
  csi:
    driver: file.csi.azure.com
    volumeAttributes: 
      resourceGroup: mc_c4ngpl-k8-resources_c4ngpl-k8_southeastasia
      storageAccount: mysqlstorage
      shareName: database
      folderName: mysql
      server: mysqlstorage.file.core.windows.net
      secretnamespace: mysql
      secretName: mysql-storage-secret
      skuName: Standard_LRS
    volumeHandle: mc_c4ngpl-k8-resources_c4ngpl-k8_southeastasia#mysqlstorage#database#mysql
    nodeStageSecretRef:
      name: mysql-storage-secret
      namespace: mysql
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=999
  - gid=999
  - cache=strict
  - mfsymlinks
  - nosharesock
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem