apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgis-tls
  namespace: postgis
spec:
  dnsNames:
  - postgis.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: postgis-tls