apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: postgis-pv
  namespace: postgis
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    name: postgis-pvc
    namespace: postgis
  csi:
    driver: file.csi.azure.com
    volumeAttributes: 
      resourceGroup: {"resource_group_name"}_{"location"}
      storageAccount: {"storage_account_name"}
      shareName: {"share_name"}
      folderName: postgis
      server: {"storage_account_name"}.file.core.windows.net
      secretnamespace: postgis
      secretName: postgis-storage-secret
      skuName: Standard_LRS
    volumeHandle: {"resource_group_name"}_{"location"}#{"storage_account_name"}#{"share_name"}#postgis
    nodeStageSecretRef:
      name: postgis-storage-secret
      namespace: postgis
  mountOptions:
  - dir_mode=0700
  - file_mode=0600
  - uid=999
  - gid=999
  - cache=strict
  - mfsymlinks
  - nosharesock
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem