apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: postgis-pv
  namespace: postgis
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    name: postgis-pvc
    namespace: postgis
  csi:
    driver: file.csi.azure.com
    volumeAttributes: 
      resourceGroup: mc_c4ngpl-k8-resources_c4ngpl-k8_southeastasia
      storageAccount: mysqlstorage
      shareName: database
      folderName: postgis
      server: mysqlstorage.file.core.windows.net
      secretnamespace: postgis
      secretName: postgis-storage-secret
      skuName: Standard_LRS
    volumeHandle: mc_c4ngpl-k8-resources_c4ngpl-k8_southeastasia#mysqlstorage#database#postgis
    nodeStageSecretRef:
      name: postgis-storage-secret
      namespace: postgis
  mountOptions:
  - dir_mode=0700
  - file_mode=0600
  - uid=999
  - gid=999
  - cache=strict
  - mfsymlinks
  - nosharesock
  - nobrl
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  volumeMode: Filesystem